services:
  redis:
    image: redis:7-alpine
    container_name: devops_redis
    ports:
      - "6379:6379"
    networks:
      - devops_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    container_name: devops_web
    image: luizvalencafilho/devops-monitor:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - devops_network
    volumes:
      - .:/app

  worker:
    build: .
    container_name: devops_worker
    image: luizvalencafilho/devops-monitor-worker:latest
    command: python celery_worker.py
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - devops_network
    volumes:
      - .:/app

networks:
  devops_network:
    driver: bridge
